spring:
  datasource:
    url: jdbc:postgresql://database/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres

#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true

bbb:
  client-mode: stub
  url: https://roggired.ru/bigbluebutton
  secret: ${BBB_SECRET:secret}
  logout-url: http://localhost:8081
  error-redirect-url: http://localhost:8081
  duration-in-minutes: 70

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
  model-converters:
    pageable-converter:
      enabled: true

security:
  dev-only:
    api-key-header: X-Sexit-Api-Key
    psycho:
      api-key: psycho-api-key
      id: b934ff51-c5fe-45d9-b259-f67d1999ccc2
      username: psycho
      email: psycho@example.com
      first-name: Psycho
      last-name: Psycho
    psycho-friend:
      api-key: psycho-friend-api-key
      id: 1fd6d68c-38a2-439a-a22f-1737a65c149e
      username: psycho_friend@example.com
      email: psycho_friend@example.com
      first-name: Psycho
      last-name: Friend
    client:
      api-key: client-api-key
      id: 8c3959e3-f87b-4828-a645-509525979bfb
      username: client@example.com
      email: client@example.com
      first-name: Client
      last-name: Client
    admin:
      api-key: admin-api-key
      id: de061760-613b-4c0f-937b-1db593b2ac64
      username: admin@example.com
      email: admin@example.com
      first-name: Admin
      last-name: Admin
  keycloak:
    base-url: http://localhost:31502
    jwks-endpoint: /realms/Sex-IT/protocol/openid-connect/certs
    authorize-endpoint: /realms/Sex-IT/protocol/openid-connect/auth
    token-endpoint: /realms/Sex-IT/protocol/openid-connect/token
    logout-endpoint: /realms/Sex-IT/protocol/openid-connect/logout
    client-id: sexit-backend
    client-secret: yiMNl8vS3Z38RYxFuOE6g6ngJsjz5KaL
    post-logout-redirect-to-newdex-url: http://localhost:3000
    use-state-for-csrf-protection: true
    state-lifetime: 5m

keycloak:
  admin:
    base-url: http://keycloak:8080/admin/realms/Sex-IT/
    authentication-base-url: http://keycloak:8080/
    admin-client-id: admin-cli
    admin-username: admin
    admin-password: admin

logging:
  level:
    ru.sexit.platform: trace
    org.apache.kafka: error
    org.springframework.kafka: error
    org.springframework.web.client: debug
#    org.springframework.security: trace
#    org.springframework.jdbc.core: debug
#    org.springframework.data: debug
#    org.hibernate: debug
#    root: info

cors:
  allowed-origins: "http://localhost:3000"
