kotlinVersion=1.9.10
springBootVersion=3.1.3

#kotlin.code.style=official
#org.gradle.warning.mode=all
#org.gradle.daemon=false
#org.gradle.vfs.watch=true
#kapt.includeCompileClasspath=false


# Http client
okhttpVersion=4.10.0
okhttpLoggingInterceptorVersion=3.14.9
retrofitVersion=2.9.0

# Persistence
postgresqlDriverVersion=42.5.1
liquibaseVersion=4.15.0

# Messaging
springKafkaVersion=2.9.5

# Docs
springDocsVersion=1.6.6

# Testing
kotestVersion=4.6.3
kotestSpringExtensionVersion=1.0.1
mockkVersion=1.12.0
testContainersVersion=1.16.0

# Files
minioVersion=8.5.1
