- hosts: 127.0.0.1
  connection: local
  gather_facts: no
  tasks:
   - name: Stop vm
     ycc_vm:
       auth:
         service_account_key: '{{ service_account_token | from_json }}'
       name: sexit-bbb
       folder_id: b1gsmcdtpsi4st75hi8n
       operation: stop
   - name: Start vm
     ycc_vm:
       auth:
         service_account_key: '{{ service_account_token | from_json }}'
       name: sexit-bbb
       folder_id: b1gsmcdtpsi4st75hi8n
       operation: start
